const items = [
  {
    id: '001',
    item_image: 'images/banner top-tees/1.png',
    rating: {
      stars:4.5,
      noOfReviews: 9300,
    },
    comany_name: 'all about you',
    item_name: 'Yellow & Off White Floral Print Mandarin Collar Puff Sleeve Cotton Top',
    current_price: 645,
    original_price: 1699,
    discount_percentage: 42,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '002',
    item_image: 'images/banner top-tees/2.png',
    rating: {
      stars:4.1,
      noOfReviews: 575,
    },
    comany_name: 'Azira',
    item_name: 'Floral Print Peplum Top',
    current_price: 699,
    original_price: 1899,
    discount_percentage: 63,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '003',
    item_image: 'images/banner top-tees/3.png',
    rating: {
      stars:4.2,
      noOfReviews: 1200,
    },
    comany_name: 'STREET 9',
    item_name: 'Floral Georgette Fitted Top',
    current_price: 399,
    original_price: 1599,
    discount_percentage: 75,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '004',
    item_image: 'images/banner top-tees/4.png',
    rating: {
      stars:4.2,
      noOfReviews: 757,
    },
    comany_name: 'EVERYDAY by ANI',
    item_name: 'Women Printed Georgette Top',
    current_price: 571,
    original_price: 2199,
    discount_percentage: 74,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '005',
    item_image: 'images/banner top-tees/5.png',
    rating: {
      stars:3.9,
      noOfReviews: 203,
    },
    comany_name: 'Kibo',
    item_name: 'V-Neck Cuffed Sleeves Top',
    current_price: 611,
    original_price: 1799,
    discount_percentage: 66,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '006',
    item_image: 'images/banner top-tees/6.png',
    rating: {
      stars:4.3,
      noOfReviews: 1200,
    },
    comany_name: 'COTLAND FASHION',
    item_name: 'Geometric Printed Cotton Peplum Top',
    current_price: 474,
    original_price: 1899,
    discount_percentage: 75,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '007',
    item_image: 'images/banner top-tees/7.png',
    rating: {
      stars:3.9,
      noOfReviews: 253,
    },
    comany_name: 'DressBerry',
    item_name: 'V-Neck White Fitted Top',
    current_price: 594,
    original_price: 1699,
    discount_percentage: 65,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '008',
    item_image: 'images/banner top-tees/8.png',
    rating: {
      stars:3.7,
      noOfReviews: 6,
    },
    comany_name: 'Roadster',
    item_name: 'The Life Co. Dolman Sleeves Boxy Top',
    current_price: 379,
    original_price: 899,
    discount_percentage: 60,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '009',
    item_image: 'images/boohooMan/9.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Men Solid Track Pants',
    current_price: 1399,
    original_price: 2799,
    discount_percentage: 50,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '010',
    item_image: 'images/boohooMan/10.png',
    rating: {
      stars:3.2,
      noOfReviews: 5,
    },
    comany_name: 'boohooMAN',
    item_name: 'Typography Printed Pure Cotton Co-Ord Set',
    current_price: 2049,
    original_price: 4099,
    discount_percentage: 50,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '011',
    item_image: 'images/boohooMan/11.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Embroidered Baseball Cap',
    current_price: 901,
    original_price: 2199,
    discount_percentage: 59,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '012',
    item_image: 'images/boohooMan/12.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Printed Oversized Co-Ords Set',
    current_price: 2474,
    original_price: 4949,
    discount_percentage: 50,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '013',
    item_image: 'images/boohooMan/13.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Varsity Print Oversized Pullover',
    current_price: 1259,
    original_price: 2799,
    discount_percentage: 55,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '014',
    item_image: 'images/boohooMan/14.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Men Shorts',
    current_price: 1099,
    original_price: 1999,
    discount_percentage: 45,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '015',
    item_image: 'images/boohooMan/15.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Cotton Printed Hooded Oversized Sweatshirt',
    current_price: 1759,
    original_price: 3199,
    discount_percentage: 45,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '016',
    item_image: 'images/boohooMan/16.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Graphic Printed Hooded Oversized Sweatshirt With Kangaroo Pocket',
    current_price: 1599,
    original_price: 3199,
    discount_percentage: 50,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
  {
    id: '017',
    item_image: 'images/boohooMan/17.png',
    rating: {
      stars:4.4,
      noOfReviews: 11,
    },
    comany_name: 'boohooMAN',
    item_name: 'Graphic Printed Back Hooded Sweatshirt',
    current_price: 1594,
    original_price: 2899,
    discount_percentage: 45,
    return_period: 14,
    delivery_date:'30 Jul 2024',
  },
]